export const GET_MOVIE_LIST_PAGING_REQUEST =
  "movie-list/GET_MOVIE_LIST_PAGING_REQUEST";
export const GET_MOVIE_LIST_PAGING_SUCCESS =
  "movie-list/GET_MOVIE_LIST_PAGING_SUCCESS";
export const GET_MOVIE_LIST_PAGING_FAILED =
  "movie-list/GET_MOVIE_LIST_PAGING_FAILED";
