export const GET_MOVIE_LIST_REQUEST = "movie/GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "movie/GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "movie/GET_MOVIE_LIST_FAILED";
