export const GET_MOVIE_DETAIL_REQUEST = "movie/GET_MOVIE_DETAIL_REQUEST";
export const GET_MOVIE_DETAIL_SUCCESS = "movie/GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "movie/GET_MOVIE_DETAIL_FAILED";
