export const GET_CURRENT_ACCOUNT_REQUEST =
  "account/GET_CURRENT_ACCOUNT_REQUEST";
export const GET_CURRENT_ACCOUNT_SUCCESS =
  "account/GET_CURRENT_ACCOUNT_SUCCESS";
export const GET_CURRENT_ACCOUNT_FAILED = "account/GET_CURRENT_ACCOUNT_FAILED";
