export const GET_MOVIE_SHOWTIMES_REQUEST = "movie/GET_MOVIE_SHOWTIMES_REQUEST";
export const GET_MOVIE_SHOWTIMES_SUCCESS = "movie/GET_MOVIE_SHOWTIMES_SUCCESS";
export const GET_MOVIE_SHOWTIMES_FAILED = "movie/GET_MOVIE_SHOWTIMES_FAILED";
