export const GET_CINEMA_LIST_REQUEST = "cinema/GET_CINEMA_LIST_REQUEST";
export const GET_CINEMA_LIST_SUCCESS = "cinema/GET_CINEMA_LIST_SUCCESS";
export const GET_CINEMA_LIST_FAILED = "cinema/GET_CINEMA_LIST_FAILED";
