export const GET_MOVIE_PAGING_REQUEST = "movie/GET_MOVIE_PAGING_REQUEST";
export const GET_MOVIE_PAGING_SUCCESS = "movie/GET_MOVIE_PAGING_SUCCESS";
export const GET_MOVIE_PAGING_FAILED = "movie/GET_MOVIE_PAGING_FAILED";
